inherit_from: .rubocop_todo.yml

# Support all non EOL rubies
AllCops:
  TargetRubyVersion: 2.4

MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 100

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
    - 'sensu-plugins-windows.gemspec'

Style/SafeNavigation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf # 99% of the maintainers use some unix and so we need to assume that linux line endings are used
